#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate knowledge-base/README.md — an entry point for clinicians.

Eleven analysis files with no index. A veterinarian arriving with a specific
question ("does this cover hypertension? what does it say is *unresolved*?") had
to open them one at a time, and the thing they most need — **what this project
admits it cannot answer** — was buried at the bottom of each file.

So the index leads with coverage and with gaps, not with a file listing. For a
clinical reader the gaps are the more useful column: they are where their own
knowledge is worth more than anything written here, and they are the shortest
route to a correctable claim.

Generated, never typed, and checked by `check_kb_hygiene.py kb-index` — a
hand-maintained index of a corpus this active would be wrong within a week.

Usage:
  build_kb_index.py            # write knowledge-base/README.md
  build_kb_index.py --check    # exit 1 if stale
Standard library only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
KB = REPO / "knowledge-base"
OUT = KB / "README.md"
OUT_ZH = KB / "README.zh.md"
GENERATED = "<!-- GENERATED by tools/build_kb_index.py — do not edit -->"

WHY = re.compile(r"^>?\s*\*\*Why this file exists\*\*[:：]\s*(.+)$", re.M)
GAPHEAD = re.compile(r"^##+\s*\d*\.?\s*(?:Genuine gaps|Gaps worth closing|"
                     r"What (?:this|the) (?:file|project) cannot|Open questions)",
                     re.I | re.M)


def summarise(path: Path) -> tuple[str, str, int, int, str]:
    """(title, why, pmid count, excerpt count, first named gap)."""
    text = path.read_text(encoding="utf-8")
    m = re.search(r"^#\s+(.+)$", text, re.M)
    title = m.group(1).strip() if m else path.stem

    w = WHY.search(text)
    why = re.sub(r"\s+", " ", w.group(1)).strip() if w else ""
    why = re.sub(r"`([^`]+)`", r"\1", why)
    if len(why) > 240:
        why = why[:237].rsplit(" ", 1)[0] + "…"

    head, _, tail = text.partition("## 原文摘录")
    pmids = len(set(re.findall(r"\*\*PMID (\d+)\*\*", tail)))
    excerpts = len([l for l in tail.splitlines()
                    if l.startswith("> ") and not l.startswith("> ⚠️")
                    and "**" not in l])

    gap = ""
    g = GAPHEAD.search(head)
    if g:
        after = head[g.end():g.end() + 900]
        for line in after.splitlines():
            s = line.strip().lstrip("-*0123456789. ").strip()
            s = re.sub(r"\*\*|`", "", s)
            if len(s) > 25 and not s.startswith(("|", ">", "#")):
                gap = s[:150] + ("…" if len(s) > 150 else "")
                break
    return title, why, pmids, excerpts, gap


def render() -> str:
    rows, details = [], []
    for f in sorted(KB.glob("*.md")):
        if f.name == "README.md":
            continue
        if f.name.endswith(".zh.md"):
            continue          # translations are listed against their English original
        title, why, pmids, excerpts, gap = summarise(f)
        rows.append(f"| [`{f.name}`]({f.name}) | {pmids} | {excerpts} |")
        block = [f"### [`{f.name}`]({f.name})", "", f"**{title}**", ""]
        if why:
            block += [why, ""]
        zh = f.with_name(f.name[:-3] + ".zh.md")
        line = f"*{pmids} papers, {excerpts} verbatim excerpts.*"
        if zh.exists():
            line += f"  ·  **中文版: [`{zh.name}`]({zh.name})**"
        block += [line, ""]
        if gap:
            block += [f"> ⚠️ **Stated gap:** {gap}", ""]
        details.append("\n".join(block))

    total_p = sum(int(r.split("|")[2]) for r in rows)
    total_e = sum(int(r.split("|")[3]) for r in rows)

    return f"""{GENERATED}

# Knowledge base — index for clinicians and researchers

These are **analysis notes, not owner material.** They are written in English,
they carry verbatim source excerpts, and they state explicitly where the
evidence runs out. For owner-facing material see [`../guides/`](../guides/) or
the [published site](https://polyketide.github.io/catmed/).

**{len(rows)} files, {total_p} papers, {total_e} verbatim excerpts**, every one
re-checked byte-for-byte against its archived PubMed record on every commit.

## If you are a veterinarian or a researcher

**The most useful thing you can do here is tell us something is wrong.** Three
issue templates exist for exactly that:

| | For |
|---|---|
| [Challenge a figure](../../../issues/new?template=01-challenge-a-figure.yml) | a number here is wrong, misattributed, or overstated |
| [Clinical review](../../../issues/new?template=02-clinical-review.yml) | the reading is defensible on paper and wrong in practice |
| [Propose coverage](../../../issues/new?template=03-propose-coverage.yml) | a condition owners keep facing that this does not cover |

**Clinical experience without a citation is welcome.** How it is recorded —
without either dismissing it or laundering it into evidence it is not — is set
out in [`../docs/LITERATURE-PIPELINE-SOP.md`](../docs/LITERATURE-PIPELINE-SOP.md) §10.

The **⚠️ Stated gap** lines below are where this project has already searched
and found nothing. Those are the fastest places for your knowledge to be worth
more than anything written here.

## At a glance

| File | Papers | Excerpts |
|---|---|---|
{chr(10).join(rows)}

## The files

{chr(10).join(details)}
"""


def render_zh() -> str:
    """Chinese index. Deliberately NOT a translation of the English one.

    A Chinese-reading veterinarian needs the same two things — what is covered,
    and what this project admits it cannot answer — but the notes themselves are
    in English, and saying so plainly up front is more useful than hiding it.
    The per-file summaries stay in English because they are lifted verbatim from
    the files; translating them here would create a second, unverified rendering
    of text that already exists — the failure mode this whole project is built
    against."""
    rows = []
    for f in sorted(KB.glob("*.md")):
        if f.name in ("README.md", "README.zh.md") or f.name.endswith(".zh.md"):
            continue
        title, why, pmids, excerpts, gap = summarise(f)
        zh = f.with_name(f.name[:-3] + ".zh.md")
        mark = f" · [中文版]({zh.name})" if zh.exists() else ""
        rows.append(f"| [`{f.name}`]({f.name}){mark} | {pmids} | {excerpts} |")

    return f"""{GENERATED}

# 知识库 · 给兽医与研究者的索引

**这些是分析用笔记，不是给主人读的材料。** 它们**以英文写成**，附带逐字原文摘录，
并且明确写出证据在哪里用尽。给主人的中文材料见
[`../guides/`](../guides/) 或 [已发布站点](https://polyketide.github.io/catmed/)。

⚠️ **关于语言的实话**：目前只有
[`hyperthyroidism-and-kidney-disease.zh.md`](hyperthyroidism-and-kidney-disease.zh.md)
有中文版，其余笔记均为英文。**这是一个已知缺口，不是设计意图**——见
[`../docs/LITERATURE-PIPELINE-SOP.md`](../docs/LITERATURE-PIPELINE-SOP.md) §11 的待做清单。

**无论哪个语言版本，文末的「原文摘录」一律是英文原句，不翻译。** 正文是解读、可以争论；
摘录是证据，逐字受同一套 CI 校验。**如需引用，请引用摘录中的原句，而不是任何语言的正文。**

## 如果你是兽医或研究者

**你在这里能做的最有价值的事，是告诉我们哪里错了。** 三个 issue 模板正是为此存在：

| | 用于 |
|---|---|
| [挑战某个数字](../../../issues/new?template=01-challenge-a-figure.yml) | 这里的某个数字是错的、张冠李戴的，或被夸大了 |
| [临床复核](../../../issues/new?template=02-clinical-review.yml) | 纸面上说得通，实践中是错的 |
| [提议新覆盖](../../../issues/new?template=03-propose-coverage.yml) | 主人反复遇到、而这里没有覆盖的病 |

**没有文献引用的临床经验同样欢迎。** 它会被如何记录——既不打发掉，也不洗成它不是的那种证据——
写在 [`../docs/LITERATURE-PIPELINE-SOP.md`](../docs/LITERATURE-PIPELINE-SOP.md) §10。

英文索引 [`README.md`](README.md) 里的 **⚠️ Stated gap** 各行，
是本项目**已经检索过、且确认没有找到**的地方。**那些是你的知识比这里任何文字都值钱的位置**，
也是最短的纠错路径。

## 文件一览

| 文件 | 论文数 | 逐字摘录 |
|---|---|---|
{chr(10).join(rows)}

每份文件的英文摘要、以及它自陈的空白，见 [`README.md`](README.md)。
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    pairs = [(OUT, render()), (OUT_ZH, render_zh())]
    if args.check:
        stale = [p.name for p, c in pairs
                 if (p.read_text(encoding="utf-8") if p.exists() else None) != c]
        if stale:
            print(f"KB_INDEX: FAIL — stale: {', '.join(stale)}")
            print("Run: python3 tools/build_kb_index.py")
            return 1
        print("KB_INDEX: PASS")
        return 0
    for path, content in pairs:
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
