#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate knowledge-base/README.md — an entry point for clinicians.

Eleven analysis files with no index. A veterinarian arriving with a specific
question ("does this cover hypertension? what does it say is *unresolved*?") had
to open them one at a time, and the thing they most need — **what this project
admits it cannot answer** — was buried at the bottom of each file.

So the index leads with coverage and with gaps, not with a file listing. For a
clinical reader the gaps are the more useful column: they are where their own
knowledge is worth more than anything written here, and they are the shortest
route to a correctable claim.

Generated, never typed, and checked by `check_kb_hygiene.py kb-index` — a
hand-maintained index of a corpus this active would be wrong within a week.

Usage:
  build_kb_index.py            # write knowledge-base/README.md
  build_kb_index.py --check    # exit 1 if stale
Standard library only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
KB = REPO / "knowledge-base"
OUT = KB / "README.md"
GENERATED = "<!-- GENERATED by tools/build_kb_index.py — do not edit -->"

WHY = re.compile(r"^>?\s*\*\*Why this file exists\*\*[:：]\s*(.+)$", re.M)
GAPHEAD = re.compile(r"^##+\s*\d*\.?\s*(?:Genuine gaps|Gaps worth closing|"
                     r"What (?:this|the) (?:file|project) cannot|Open questions)",
                     re.I | re.M)


def summarise(path: Path) -> tuple[str, str, int, int, str]:
    """(title, why, pmid count, excerpt count, first named gap)."""
    text = path.read_text(encoding="utf-8")
    m = re.search(r"^#\s+(.+)$", text, re.M)
    title = m.group(1).strip() if m else path.stem

    w = WHY.search(text)
    why = re.sub(r"\s+", " ", w.group(1)).strip() if w else ""
    why = re.sub(r"`([^`]+)`", r"\1", why)
    if len(why) > 240:
        why = why[:237].rsplit(" ", 1)[0] + "…"

    head, _, tail = text.partition("## 原文摘录")
    pmids = len(set(re.findall(r"\*\*PMID (\d+)\*\*", tail)))
    excerpts = len([l for l in tail.splitlines()
                    if l.startswith("> ") and not l.startswith("> ⚠️")
                    and "**" not in l])

    gap = ""
    g = GAPHEAD.search(head)
    if g:
        after = head[g.end():g.end() + 900]
        for line in after.splitlines():
            s = line.strip().lstrip("-*0123456789. ").strip()
            s = re.sub(r"\*\*|`", "", s)
            if len(s) > 25 and not s.startswith(("|", ">", "#")):
                gap = s[:150] + ("…" if len(s) > 150 else "")
                break
    return title, why, pmids, excerpts, gap


def render() -> str:
    rows, details = [], []
    for f in sorted(KB.glob("*.md")):
        if f.name == "README.md":
            continue
        title, why, pmids, excerpts, gap = summarise(f)
        rows.append(f"| [`{f.name}`]({f.name}) | {pmids} | {excerpts} |")
        block = [f"### [`{f.name}`]({f.name})", "", f"**{title}**", ""]
        if why:
            block += [why, ""]
        block += [f"*{pmids} papers, {excerpts} verbatim excerpts.*", ""]
        if gap:
            block += [f"> ⚠️ **Stated gap:** {gap}", ""]
        details.append("\n".join(block))

    total_p = sum(int(r.split("|")[2]) for r in rows)
    total_e = sum(int(r.split("|")[3]) for r in rows)

    return f"""{GENERATED}

# Knowledge base — index for clinicians and researchers

These are **analysis notes, not owner material.** They are written in English,
they carry verbatim source excerpts, and they state explicitly where the
evidence runs out. For owner-facing material see [`../guides/`](../guides/) or
the [published site](https://polyketide.github.io/catmed/).

**{len(rows)} files, {total_p} papers, {total_e} verbatim excerpts**, every one
re-checked byte-for-byte against its archived PubMed record on every commit.

## If you are a veterinarian or a researcher

**The most useful thing you can do here is tell us something is wrong.** Three
issue templates exist for exactly that:

| | For |
|---|---|
| [Challenge a figure](../../../issues/new?template=01-challenge-a-figure.yml) | a number here is wrong, misattributed, or overstated |
| [Clinical review](../../../issues/new?template=02-clinical-review.yml) | the reading is defensible on paper and wrong in practice |
| [Propose coverage](../../../issues/new?template=03-propose-coverage.yml) | a condition owners keep facing that this does not cover |

**Clinical experience without a citation is welcome.** How it is recorded —
without either dismissing it or laundering it into evidence it is not — is set
out in [`../docs/LITERATURE-PIPELINE-SOP.md`](../docs/LITERATURE-PIPELINE-SOP.md) §10.

The **⚠️ Stated gap** lines below are where this project has already searched
and found nothing. Those are the fastest places for your knowledge to be worth
more than anything written here.

## At a glance

| File | Papers | Excerpts |
|---|---|---|
{chr(10).join(rows)}

## The files

{chr(10).join(details)}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = render()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if args.check:
        if current != content:
            print("KB_INDEX: FAIL — knowledge-base/README.md is stale.")
            print("Run: python3 tools/build_kb_index.py")
            return 1
        print("KB_INDEX: PASS")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
